version: '3'

services:
  ros_system:
    build:
      context: .
      dockerfile: Dockerfile
    image: mlff:latest
    container_name: mlff_system
    volumes:
      - ./:/home/ros_ws
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    network_mode: "host"
    privileged: true
    command: ./launch.sh
    restart: unless-stopped